// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqCUHAEQhmNGIymFR4o3Gx7MRj7UbcFzk',
    appId: '1:1000640327586:web:6d235d05f756b474d58cfb',
    messagingSenderId: '1000640327586',
    projectId: 'taste-point-a6323',
    authDomain: 'taste-point-a6323.firebaseapp.com',
    storageBucket: 'taste-point-a6323.firebasestorage.app',
    measurementId: 'G-66CEGG0JKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApIUmOY1rZ4bOuNNaN0rOxh83qFXkj9RQ',
    appId: '1:1000640327586:android:d031f693092b65d4d58cfb',
    messagingSenderId: '1000640327586',
    projectId: 'taste-point-a6323',
    storageBucket: 'taste-point-a6323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAThWa4_5FY4FTa3rM_KUE5gIM-QaQASe0',
    appId: '1:1000640327586:ios:e82bede7bd38eb9bd58cfb',
    messagingSenderId: '1000640327586',
    projectId: 'taste-point-a6323',
    storageBucket: 'taste-point-a6323.firebasestorage.app',
    iosBundleId: 'com.example.tatifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAThWa4_5FY4FTa3rM_KUE5gIM-QaQASe0',
    appId: '1:1000640327586:ios:e82bede7bd38eb9bd58cfb',
    messagingSenderId: '1000640327586',
    projectId: 'taste-point-a6323',
    storageBucket: 'taste-point-a6323.firebasestorage.app',
    iosBundleId: 'com.example.tatifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqCUHAEQhmNGIymFR4o3Gx7MRj7UbcFzk',
    appId: '1:1000640327586:web:b90e440516487d16d58cfb',
    messagingSenderId: '1000640327586',
    projectId: 'taste-point-a6323',
    authDomain: 'taste-point-a6323.firebaseapp.com',
    storageBucket: 'taste-point-a6323.firebasestorage.app',
    measurementId: 'G-6LNQCP29XZ',
  );
}
